= RabbitMQ Stream Java Client

The RabbitMQ Stream Java Client is a Java library to communicate with
the https://github.com/rabbitmq/rabbitmq-stream[RabbitMQ Stream Plugin].
It allows to create and delete streams, as well as to publish to and consume from
these streams.

The client ships also with a
https://rabbitmq.github.io/rabbitmq-stream-java-client/snapshot/htmlsingle/#the-performance-tool[performance tool].

Please refer to the https://rabbitmq.github.io/rabbitmq-stream-java-client/snapshot/htmlsingle/[documentation]
to find out more.

== Project Maturity

The project is in early stages of development and is considered experimental.
It is not ready for production use. Features and API are subject to change.

== Support

* For questions: https://groups.google.com/forum/#!forum/rabbitmq-users[RabbitMQ Users]
* For bugs and feature requests: https://github.com/rabbitmq/rabbitmq-stream-java-client/issues[GitHub Issues]

The project is currently under development, there is no guarantee yet that it will be maintained and supported
in the future (read: you are welcome to experiment with it and give feedback, but please do not base
your whole business on it).

== How to Use

=== Pre-requisites

The library requires Java 8 or more.

=== Documentation

https://rabbitmq.github.io/rabbitmq-stream-java-client/snapshot/htmlsingle/[Reference documentation]

== Build Instructions

You need JDK 1.8 or more installed.

To build the JAR file:

----
./mvnw clean package -DskipITs -DskipTests
----

To launch the test suite (requires a local RabbitMQ node with stream plugin enabled):

----
./mvnw verify
----

== Copyright and License

(c) 2020, VMware Inc or its affiliates.

Double licensed under the ASL2 and MPL1.1. See link:LICENSE[LICENSE] for details.
