= RabbitMQ Stream Java Client

image:https://maven-badges.herokuapp.com/maven-central/com.rabbitmq/stream-client/badge.svg["Maven Central", link="https://maven-badges.herokuapp.com/maven-central/com.rabbitmq/stream-client"]
image:https://github.com/rabbitmq/rabbitmq-stream-java-client/workflows/Build%20(Linux,%20Single%20Active%20Consumer)/badge.svg?branch=single-active-consumer["Build Status", link="https://github.com/rabbitmq/rabbitmq-stream-java-client/actions/workflows/test-linux-sac.yml"]
image:https://codecov.io/gh/rabbitmq/rabbitmq-stream-java-client/branch/main/graph/badge.svg?token=CFZ6EHW47J["Code Coverage", link="https://codecov.io/gh/rabbitmq/rabbitmq-stream-java-client"]

The RabbitMQ Stream Java Client is a Java library to communicate with
the https://rabbitmq.com/stream.html[RabbitMQ Stream Plugin].
It allows to create and delete streams, as well as to publish to and consume from
these streams.

The client ships also with a
https://rabbitmq.github.io/rabbitmq-stream-java-client/sac/htmlsingle/#the-performance-tool[performance tool].

Please refer to the https://rabbitmq.github.io/rabbitmq-stream-java-client/stable/htmlsingle/[documentation]
(https://rabbitmq.github.io/rabbitmq-stream-java-client/sac/pdf/index.pdf[PDF])
to find out more.

== Project Maturity

The project is in development and stabilization phase.
Features and API are subject to change, but https://rabbitmq.github.io/rabbitmq-stream-java-client/sac/htmlsingle/#stability-of-programming-interfaces[breaking changes] will be kept to a minimum.

== Support

* For questions: https://groups.google.com/forum/#!forum/rabbitmq-users[RabbitMQ Users]
* For bugs and feature requests: https://github.com/rabbitmq/rabbitmq-stream-java-client/issues[GitHub Issues]

== How to Use

=== Pre-requisites

The library requires Java 8 or later. Java 11 is recommended.

=== Documentation

==== Snapshot

* https://rabbitmq.github.io/rabbitmq-stream-java-client/sac/htmlsingle/[Reference documentation]
* https://rabbitmq.github.io/rabbitmq-stream-java-client/sac/api/com/rabbitmq/stream/package-summary.html[API documentation]

== Versioning

The RabbitMQ Stream Java Client is in development and stabilization phase.
When the stabilization phase ends, a 1.0.0 version will be cut, and
https://semver.org/[semantic versioning] is likely to be enforced.

Before reaching the stable phase, the client will use a versioning scheme of `[0.MINOR.PATCH]` where:

* `0` indicates the project is still in a stabilization phase.
* `MINOR` is a 0-based number incrementing with each new release cycle. It generally reflects significant changes like new features and potentially some programming interfaces changes.
* `PATCH` is a 0-based number incrementing with each service release, that is bux fixes.

Breaking changes between releases can happen but will be kept to a minimum.

== Build Instructions

You need JDK 1.8 or more installed.

To build the JAR file:

----
./mvnw clean package -DskipITs -DskipTests
----

=== Running Tests with Docker

Launch the broker:

----
docker run -it --rm --name rabbitmq -p 5552:5552 -p 5672:5672 \
    -e RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS='-rabbitmq_stream advertised_host localhost' \
    pivotalrabbitmq/rabbitmq-stream:sac
----

Enable the stream plugin:

----
docker exec rabbitmq rabbitmq-plugins enable rabbitmq_stream
----

Launch the tests:

----
./mvnw test -Drabbitmqctl.bin=DOCKER:rabbitmq
----

=== Running Tests with a Local Broker

To launch the test suite (requires a local RabbitMQ node with stream plugin enabled):

----
./mvnw verify -Drabbitmqctl.bin=/path/to/rabbitmqctl
----

== Code Format

The project uses the https://github.com/google/google-java-format[Google Java Format]. Read
the documentation to support the format in your
https://github.com/google/google-java-format#intellij-android-studio-and-other-jetbrains-ides[favorite]
https://github.com/google/google-java-format#eclipse[IDE].

Please launch the `./mvnw spotless:apply` command to format your changes before committing.

== Copyright and License

(c) 2020-2022, VMware Inc or its affiliates.

Double licensed under the MPL2.0 and ASL2. See link:LICENSE[LICENSE] for details.
