= RabbitMQ Stream Java Client

image:https://github.com/rabbitmq/rabbitmq-stream-java-client/workflows/Build%20(Linux)/badge.svg?branch=main["Build Status", link="https://github.com/rabbitmq/rabbitmq-stream-java-client/actions?query=workflow%3A%22Build+%28Linux%29%22+branch%3Amain"]

The RabbitMQ Stream Java Client is a Java library to communicate with
the https://github.com/rabbitmq/rabbitmq-server/tree/v3.9.x/deps/rabbitmq_stream[RabbitMQ Stream Plugin].
It allows to create and delete streams, as well as to publish to and consume from
these streams.

The client ships also with a
https://rabbitmq.github.io/rabbitmq-stream-java-client/snapshot/htmlsingle/#the-performance-tool[performance tool].

Please refer to the https://rabbitmq.github.io/rabbitmq-stream-java-client/snapshot/htmlsingle/[documentation]
(https://rabbitmq.github.io/rabbitmq-stream-java-client/snapshot/pdf/index.pdf[PDF])
to find out more.

== Project Maturity

The project is in early stages of development and is considered experimental.
It is not ready for production use. Features and API are subject to change.

== Support

* For questions: https://groups.google.com/forum/#!forum/rabbitmq-users[RabbitMQ Users]
* For bugs and feature requests: https://github.com/rabbitmq/rabbitmq-stream-java-client/issues[GitHub Issues]

The project is currently under development, there is no guarantee yet that it will be maintained and supported
in the future (read: you are welcome to experiment with it and give feedback, but please do not base
your whole business on it).

== How to Use

=== Pre-requisites

The library requires Java 8 or more.

=== Documentation

* https://rabbitmq.github.io/rabbitmq-stream-java-client/snapshot/htmlsingle/[Reference documentation]
* https://rabbitmq.github.io/rabbitmq-stream-java-client/snapshot/api/com/rabbitmq/stream/package-summary.html[API documentation]

== Build Instructions

You need JDK 1.8 or more installed.

To build the JAR file:

----
./mvnw clean package -DskipITs -DskipTests
----

=== Running Tests with Docker

Launch the broker:

----
docker run -it --rm --name rabbitmq --network host pivotalrabbitmq/rabbitmq-stream
----

Launch the tests:

----
./mvnw test -Drabbitmqctl.bin=DOCKER:rabbitmq
----

=== Running Tests

To launch the test suite (requires a local RabbitMQ node with stream plugin enabled):

----
./mvnw verify -Drabbitmqctl.bin=/path/to/rabbitmqctl
----

== Code Format

The project uses the https://github.com/google/google-java-format[Google Java Format]. Read
the documentation to support the format in your
https://github.com/google/google-java-format#intellij-android-studio-and-other-jetbrains-ides[favorite]
https://github.com/google/google-java-format#eclipse[IDE].

Please launch the `./mvnw spotless:apply` command to format your changes before committing.

== Copyright and License

(c) 2020-2021, VMware Inc or its affiliates.

Double licensed under the MPL2.0 and ASL2. See link:LICENSE[LICENSE] for details.
