== What is a RabbitMQ Stream?

A RabbitMQ stream is a persistent and replicated data structure that models
an https://en.wikipedia.org/wiki/Append-only[append-only log]. It differs from the classical
RabbitMQ queue in the way message consumption works. In a classical RabbitMQ queue,
consuming removes messages from the queue. In a RabbitMQ stream, consuming leaves
the stream intact. So the content of a stream can be read and re-read without
impact or destructive effect.

None of the stream or classical queue data structure is better than the other,
they are usually suited for different use cases.

== When to Use RabbitMQ Stream?

RabbitMQ Stream was developed to cover the following messaging use cases:

* _Large fan-outs:_ when several consumer applications need to read the same messages.
* _Replay / Time-traveling:_ when consumer applications need to read the whole
history of data or from a given point in a stream.
* _Throughput performance:_ when higher throughput than with other protocols
(AMQP, STOMP, MQTT) is required.
* _Large logs:_ when large amount of data need to be stored, with minimal
in-memory overhead.

== Other Way to Use Streams in RabbitMQ

It is also possible to use the stream abstraction in RabbitMQ
with the AMQP 0-9-1 protocol. Instead of consuming from a stream
with the stream protocol, one consumes from a "stream-powered" queue with
the AMQP 0-9-1 protocol. A "stream-powered" queue is a special type of queue that
is backed up with a stream infrastructure layer and adapted to
provide the stream semantics (mainly non-destructive reading).

Using such a queue has the advantage to provide the features
inherent to the stream abstraction (append-only structure, non-destructive
reading) with any AMQP 0-9-1 client library. This is clearly
interesting when considering the maturity of AMQP 0-9-1 client libraries
and the ecosystem around AMQP 0-9-1.

But by using it, one does not benefit from the performance
of the stream protocol, which has been designed for performance in mind,
whereas AMQP 0-9-1 is a more general-purpose protocol.

It is not possible to use "stream-powered" queues with the stream Java client,
you need to use an AMQP 0-9-1 client library.

== Guarantees

RabbitMQ stream provides at-least-once guarantees thanks to the
publisher confirm mechanism, which is supported by the stream Java client.

Message <<api.adoc#outbound-message-de-deduplication,de-duplication>>
is also supported on the publisher side.

[[stream-client-overview]]
== Stream Client Overview

The RabbitMQ Stream Java Client implements the
https://github.com/rabbitmq/rabbitmq-server/blob/v3.9.x/deps/rabbitmq_stream/docs/PROTOCOL.adoc[RabbitMQ Stream protocol]
and avoids dealing with low-level concerns by providing high-level functionalities
to build fast, efficient, and robust client applications.

* _administrate streams (creation/deletion) directly from applications._ This
can also be useful for development and testing.
* _adapt publishing throughput_ thanks to the configurable batch size and flow control.
* _avoid publishing duplicate messages_ thanks to message de-duplication.
* _consume asynchronously from streams and resume where left off_ thanks to
automatic or manual offset tracking.
* _use cluster nodes appropriately_ by letting the client decide which node to connect to - to
stream leaders for publishers to minimize inter-node traffic and to stream replicas
for consumers to offload leaders.
* _optimize resources_ thanks to automatic growing and shrinking of
connections depending on the number of publishers and consumers.
* _let the client handle network failure_ thanks to automatic connection
recovery and automatic re-subscription for consumers.

