== The Performance Tool

The library contains also a performance tool to test the RabbitMQ Stream plugin.
It is usable as an uber JAR
https://bintray.com/rabbitmq/java-tools-dev/stream-perf-test[downloadable from Bintray]
or as a https://hub.docker.com/r/pivotalrabbitmq/stream-perf-test[Docker image].
It can be built separately as well.

=== Using the Performance Tool

==== With Docker

The performance tool is available as a
https://hub.docker.com/r/pivotalrabbitmq/stream-perf-test[Docker image].
You can use the Docker image to list the available options:

.Listing the available options of the performance tool
----
docker run -it --rm pivotalrabbitmq/stream-perf-test --help
----

There are all sorts of options, if none is provided,
the tool will start publishing to and consuming from a stream created
only for the test.

When using Docker, the container running the performance tool must be able to
connect to the broker, so you have to figure out the appropriate Docker
configuration to make this possible.
You can have a look at the https://docs.docker.com/network/[Docker network documentation]
to find out more.

We show next a couple of options to easily use the Docker image.

===== With Docker Host Network Driver

This is the simplest way to run the image locally, with a local broker running in Docker as well.
The containers use the https://docs.docker.com/network/host/[host network],
this is perfect for experimenting locally.

.Running the broker and performance tool with the host network driver
----
# run the broker
docker run -it --rm --network host pivotalrabbitmq/rabbitmq-stream
# open another terminal and run the performance tool
docker run -it --rm --network host pivotalrabbitmq/stream-perf-test
----

===== With Docker Bridge Network Driver

Containers need to be able to communicate with each other with
the https://docs.docker.com/network/bridge/[bridge network driver], this
can be done by defining a network and running the containers in this network.

.Running the broker and performance tool with the bridge network driver
----
# create a network
docker network create stream-perf-test
# run the broker
docker run -it --rm --network stream-perf-test --name rabbitmq pivotalrabbitmq/rabbitmq-stream
# open another terminal and run the performance tool
docker run -it --rm --network stream-perf-test pivotalrabbitmq/stream-perf-test \
    --addresses rabbitmq:5555
----

==== With the Java Binary

The Java binary is https://bintray.com/rabbitmq/java-tools-dev/stream-perf-test[on Bintray].

To launch a run:

----
$ java -jar stream-perf-test-{version}.jar
14:49:09.695 [main] INFO  c.r.stream.perf.StreamPerfTest - Created stream stream1
14:49:09.935 [main] INFO  c.r.stream.perf.StreamPerfTest - Starting producer
1, published 356120 msg/s, confirmed 353872 msg/s, consumed 351870 msg/s, latency min/median/75th/95th/99th 3925/14539/17383/23765/31068 µs, chunk size 1724
2, published 554087 msg/s, confirmed 551654 msg/s, consumed 552472 msg/s, latency min/median/75th/95th/99th 3297/12430/15489/20140/25733 µs, chunk size 2301
3, published 663102 msg/s, confirmed 660917 msg/s, consumed 662571 msg/s, latency min/median/75th/95th/99th 3146/11914/14645/19149/24354 µs, chunk size 2484
4, published 714358 msg/s, confirmed 712882 msg/s, consumed 714016 msg/s, latency min/median/75th/95th/99th 2836/11651/14466/18840/24509 µs, chunk size 2624
5, published 732703 msg/s, confirmed 731439 msg/s, consumed 732150 msg/s, latency min/median/75th/95th/99th 2992/11868/14593/18846/24066 µs, chunk size 2771
6, published 768071 msg/s, confirmed 767277 msg/s, consumed 767941 msg/s, latency min/median/75th/95th/99th 2992/11719/14532/18388/23895 µs, chunk size 2855
7, published 794034 msg/s, confirmed 793072 msg/s, consumed 793992 msg/s, latency min/median/75th/95th/99th 2992/11607/14251/18144/23895 µs, chunk size 2864
8, published 801647 msg/s, confirmed 800804 msg/s, consumed 801628 msg/s, latency min/median/75th/95th/99th 2992/11460/14171/18063/24509 µs, chunk size 2914
...
^C
Summary: published 783246 msg/s, confirmed 782755 msg/s, consumed 782755 msg/s, latency 95th 27212 µs, chunk size 3095
----

The previous command will start publishing to and consuming from a `stream1` stream created
only for the test. The tool outputs live metrics on the console and write more
detailed metrics in a `stream-perf-test-current.txt` file that get renamed to
`stream-perf-test-yyyy-MM-dd-HHmmss.txt` when the run ends.

To see the options:

----
java -jar stream-perf-test-{version}.jar --help
----

The performance tool comes also with a completion script. You can download it and enable it in
your `~/.zshrc` file:

----
alias stream-perf-test='java -jar target/stream-perf-test.jar'
source ~/.zsh/stream-perf-test_completion
----

Note the activation requires an alias which must be `stream-perf-test`. The command can be anything
though.

==== Common Usage

===== Connection

The performance tool connects by default to localhost, on port 5555, with
default credentials (`guest`/`guest`), on the default `/` virtual host.
This can be changed with the `--uris` option:

----
java -jar stream-perf-test.jar --uris rabbitmq-stream://rabbitmq-1:5555
----

The URI follows the same rules as the
https://www.rabbitmq.com/uri-spec.html[AMQP 0.9.1 URI],
except the protocol must be `rabbitmq-stream` and TLS is not supported.
The next command shows how to set up the different elements of the URI:

----
java -jar stream-perf-test.jar \
  --uris rabbitmq-stream://guest:guest@localhost:5555/%2f
----

The option accepts several values, separated by commas. By doing so, the tool
will be able to pick another URI for its "locator" connection, in case a node
crashes:

----
java -jar stream-perf-test.jar \
  --uris rabbitmq-stream://rabbitmq-1:5555,rabbitmq-stream://rabbitmq-2:5555
----

Note the tool uses those URIs only for management purposes, it does not use them
to distribute publishers and consumers across a cluster.

===== Publishing Rate

It is possible to limit the publishing rate with the `--rate` option:

----
java -jar stream-perf-test.jar --rate 10000
----

RabbitMQ Stream can easily saturate the resources of the hardware, it can especially
max out the storage IO. Reasoning when a system is under severe constraints can
be difficult, so setting a low publishing rate can be a good idea to get familiar
with the performance tool and the semantics of streams.

===== Number of Producers and Consumers

You can set the number of producers and consumers with the `--producers` and
`--consumers` options, respectively:

----
java -jar stream-perf-test.jar --producers 5 --consumers 5
----

With the previous command, you should see a higher consuming rate than
publishing rate. It is because the 5 producers publish as fast as they can
and each consumer consume the messages from the 5 publishers. In theory
the consumer rate should be 5 times the publishing rate, but as stated previously,
the performance tool may put the broker under severe constraints, so the numbers
may not add up.

You can set a low publishing rate to verify this theory:

----
java -jar stream-perf-test.jar --producers 5 --consumers 5 --rate 10000
----

With the previous command, each publisher should publish 10,000 messages per second,
that is 50,000 messages per second overall. As each consumer consumes each published messages,
the consuming rate should be 5 times the publishing rate, that is 250,000 messages per
second. Using a small publishing rate should let plenty of resources to the system,
so the rates should tend towards those values.

===== Streams

The performance tool uses a `stream1` stream by default, the `--streams` option allows
specifying streams that will be created and used only for the test run. Note producer
and consumer counts must be set accordingly, as they are not spread across the
stream automatically. The following command will run a test with 3 streams, with
a producer and a consumer on each of them:

----
java -jar stream-perf-test.jar --streams stream1,stream2,stream3 \
                               --producers 3 --consumers 3
----

If you do not want the tool to create and delete streams for a run, because they are already created,
use the `--pre-declared` option:

----
java -jar stream-perf-test.jar --streams stream1,stream2,stream3 \
                               --producers 3 --consumers 3 \
                               --pre-declared
----

===== Publishing Batch Size

The default publishing batch size is 100, that is a publishing frame is sent every 100 messages.
The following command sets the batch size to 50 with the `--batch-size` option:

----
java -jar stream-perf-test.jar --batch-size 50
----

There is no ideal batch size, it is a tradeoff between throughput and latency.
High batch size values should increase throughput (usually good) and latency (usually not so
good), whereas low batch size should decrease throughput (usually not good) and latency (usually
good).

===== Unconfirmed Messages

A publisher can have at most 10,000 unconfirmed messages at some point. If it reaches this value,
it has to wait until the broker confirms some messages. This avoids fast publishers overwhelming
the broker. The `--confirms` option allows changing the default value:

----
java -jar stream-perf-test.jar --confirms 20000
----

High values should increase throughput at the cost of consuming more memory, whereas low values
should decrease throughput and memory consumption.

===== Message Size

The default size of a message is 10 bytes, which is rather small. The `--size` option lets you
specify a different size, usually higher, to have a value close to your use case. The next command
sets a size of 1 KB:

----
java -jar stream-perf-test.jar --size 1024
----

Note the message body size cannot be smaller that 8 bytes, as the performance tool stores
a long in each message to calculate the latency. Note also the actual size of a message will be
slightly higher, as the body is wrapped in an <<api.adoc#working-with-complex-messages,AMQP 1.0 message>>.

==== Advanced Usage

===== Retention

If you run performance tests for a long time, you might be interested in setting
a <<api.adoc#limiting-the-size-of-a-stream,retention strategy>> for
the streams the performance tool creates for a run. This
would typically avoid saturating the storage devices of your servers.
The default values are 20 GB for the maximum size of a stream and
500 MB for each segment files that composes a stream. You can change
these values with the `--max-length-bytes` and `--max-segment-size` options:

----
java -jar stream-perf-test.jar --max-length-bytes 10gb \
                               --max-segment-size 250mb
----

Both options accept units (`kb`, `mb`, `gb`, `tb`), as well as no unit to
specify a number of bytes.

===== Offset (Consumer)

Consumers start by default at the first available offset of stream, that is
the beginning of the stream if it has not been truncated (offset 0). It is possible
to specify an <<api.adoc#specifying-an-offset,offset>> to start from with the `--offset` option,
if you have existing streams and you want to consume from them at a specific offset.
The following command sets the consumer to start consuming at the very end of
a stream, as soon as new messages are published:

----
java -jar stream-perf-test.jar --offset next
----

The accepted values for `--offset` are `first` (the default), `last`, `next`,
an unsigned long for a given offset, and an ISO 8601 formatted timestamp
(eg. `2020-06-03T07:45:54Z`).

===== Offset Tracking (Consumer)

A consumer can <<api.adoc#consumer-offset-tracking,track the point>> it has reached
in a stream to be able to restart where it left off in a new incarnation.
The performance tool has the `--commit-every` option to tell consumers to commit
the offset every `x` messages to be able to measure the impact of offset tracking
in terms of throughput and storage. This feature is disabled by default.
The following command shows how to commit the offset every 100,000 messages:

----
java -jar stream-perf-test.jar --commit-every 100000
----

=== Building the Performance Tool

To build the uber JAR:

----
./mvnw clean package -Dmaven.test.skip -P performance-tool
----

Then run the tool:

----
java -jar target/stream-perf-test.jar
----