=== Setting up RabbitMQ

A RabbitMQ node with the stream plugin enabled is required. The easiest way
to get up and running is to use Docker. It is also possible to use the
generic Unix package.

==== With Docker

There are different ways to make the broker visible to the client application when running
in Docker. The next sections show a couple of options suitable for local development.

[NOTE]
.Docker on macOS
====
Docker runs on a virtual machine when using macOS, so do not expect high performance
when using RabbitMQ Stream inside Docker on a Mac.
====

===== With Docker Bridge Network Driver

This section shows how to start a broker instance for local development
(the broker Docker container and the client application are assumed to run on the
same host).

The following command creates a one-time Docker container to run RabbitMQ
with the stream plugin enabled:

.Running the stream plugin with Docker
----
docker run -it --rm --name rabbitmq -p 5551:5551 \
    -e RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-rabbitmq_stream advertised_host localhost" \
    pivotalrabbitmq/rabbitmq-stream
----

The previous command exposes only the stream port (5551), you can expose
ports for other protocols:

.Exposing the AMQP 0.9.1 and management ports:
----
docker run -it --rm --name rabbitmq -p 5551:5551 -p 5672:5672 -p 15672:15672 \
    -e RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-rabbitmq_stream advertised_host localhost" \
    pivotalrabbitmq/rabbitmq-stream
----

Refer to the official https://hub.docker.com/_/rabbitmq[RabbitMQ Docker image web page]
to find out more about its usage. Make sure to use the `pivotalrabbitmq/rabbitmq-stream`
image in the command line.

The `pivotalrabbitmq/rabbitmq-stream` Docker image is meant for development usage only. It does not
support all the features of the official Docker image, like TLS.

===== With Docker Host Network Driver

This is the simplest way to run the broker locally.
The container uses the https://docs.docker.com/network/host/[host network],
this is perfect for experimenting locally.

.Running RabbitMQ Stream with the host network driver
----
docker run -it --rm --network host pivotalrabbitmq/rabbitmq-stream
----

The command above will use the following ports: 5551 (for stream), 5672 (for AMQP),
15672 (for management plugin).

[NOTE]
.Docker Host Network Driver Support
====
The host networking driver *only works on Linux hosts*.
====

==== With the Generic Unix Package

The generic Unix package requires https://www.rabbitmq.com/which-erlang.html[Erlang] to be installed.

* Download the https://bintray.com/rabbitmq/all-dev/rabbitmq-stream[latest generic Unix alpha from Bintray].
* Follow the https://www.rabbitmq.com/install-generic-unix.html[instructions to install the generic Unix package].
* Enable the plugin `./rabbitmq-plugins enable rabbitmq_stream`.
* Start the broker `./rabbitmq-server -detached`. This starts the stream listener on port 5551.

=== Dependencies

Use your favorite build management tool to add the client dependencies to your project.

Note the client uses the https://github.com/apache/qpid-proton-j[Apache QPid Proton-J]
library for <<api.adoc#working-with-complex-messages,AMQP 1.0 message encoding and decoding>>.

==== Maven

.pom.xml
[source,xml,subs="attributes,specialcharacters"]
----
<dependencies>

  <dependency>
    <groupId>com.rabbitmq</groupId>
    <artifactId>stream-client</artifactId>
    <version>{project-version}</version>
  </dependency>

  <dependency>
    <groupId>org.apache.qpid</groupId>
    <artifactId>proton-j</artifactId>
    <version>{protonj-version}</version>
  </dependency>

</dependencies>

<repositories>

  <repository>
    <id>ossrh</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <snapshots><enabled>true</enabled></snapshots>
    <releases><enabled>false</enabled></releases>
  </repository>

</repositories>
----

==== Gradle

.build.gradle
[source,groovy,subs="attributes,specialcharacters"]
----
dependencies {
  compile "com.rabbitmq:stream-client:{project-version}"
  compile "org.apache.qpid:proton-j:{protonj-version}"
}

repositories {
  maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
  mavenCentral()
}
----